# Vector Operations

# Vector to Vector Multiplication

In [3]:
import numpy as np


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Matrix to Vector Multiplication

In [5]:
matrix = np.array([[3,4,5],
                   [6,7,8],
                   [9,10,11]])
matrix

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [7]:
np.dot(matrix, vector)

array([26, 44, 62])

In [8]:
matrix.dot(vector)

array([26, 44, 62])

# Matrix to Matrix Multiplication

# Identity Matrix (Square Matrix)

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Matrix Inverse

In [10]:
np.array([10,5,33,2])

array([10,  5, 33,  2])