# 1. Import numpy as np and see the version

In [2]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 1.25.2


# 2. How to create a 1D array?

In [8]:
# default array from a python list

array = np.array([0,1,2,3,4,5,6,7,8,9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Using .arange | It creates a 1D array using consecutive 
# numbers from 0 to 9

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# using .linspace | this creates a 1D array of 
# evenly spaced numbers between 0 and 1 (inclusive), with 5 elements

array = np.linspace(0,2,5)
array

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
# using .zeros | It creates a 1D array filled with zeros, 
# with 6 elements

array = np.zeros(6)
array

array([0., 0., 0., 0., 0., 0.])

In [7]:
type(array)

numpy.ndarray

In [10]:
# help(np.array)
np.array?

# 3. How to create a boolean array?

In [17]:
# ".ones" function usage

shape = (2,2)
np.ones(shape)

array([[1., 1.],
       [1., 1.]])

In [18]:
# Create a 3×3 numpy array of all True

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [ ]:
# extract the odd number

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])