# Matrix

In [1]:
matrix = [[0,1,2],
          [3,4,5],
          [6,7,8]]

print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [5]:
# NumPy Matrix slicing

import numpy as np

matrix = [[0,1,2],
          [3,4,5],
          [6,7,8]]

matrix = np.array(matrix)

matrix[:,1:2]

array([[1],
       [4],
       [7]])

In [6]:
# All lines and columns

matrix[:, :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# All columns from the first line

matrix[0:1, :]

array([[0, 1, 2]])

In [14]:
# All columns from the first to second lines

matrix[0:2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
# Second column from all lines

matrix[:, 1:2]

array([[1],
       [4],
       [7]])

In [19]:
# All colums beginnig from the second one

matrix[:, 1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Describe a Matrix

In [20]:
matrix.ndim

2

In [21]:
matrix.size

9

In [22]:
matrix.shape

(3, 3)

# Min and Max values

In [23]:
# max value for all elements in matrix

matrix = [[0,1,2],
          [3,4,5],
          [6,7,8]]

np.max(matrix)

8

In [24]:
# min value for all elements in matrix

np.min(matrix)

0

In [25]:
# max value for each column
# axis = 0 means columns

np.max(matrix, axis = 0)

array([6, 7, 8])

In [26]:
# min value for each column
# axis = 0 means columns

np.min(matrix, axis = 0)

array([0, 1, 2])

In [27]:
# max value for each row
# axis = 1 means rows

np.max(matrix, axis = 1)

array([2, 5, 8])

In [28]:
# min value for each row
# axis = 1 means rows

np.min(matrix, axis = 1)

array([0, 3, 6])

In [34]:
# max value for the second column

matrix = np.array([[0,1,2],
                   [3,4,5],
                   [6,7,8]])

np.max(matrix[:, 1:2])

7