## Key Concepts in Linear Algebra for Linear Regression:
#### 1. Scalars, Vectors, and Matrices:

In [4]:
import numpy as np

# A scalar is a single number.

scalar = 10

# A vector is an array of numbers (1D).
vector = [10, 12, 43, 14]

# A matrix is a 2D array of numbers.
matrix = [[10, 12, 43, 14],
          [10, 12, 43, 14]]

scalar, vector, matrix

(10, [10, 12, 43, 14], [[10, 12, 43, 14], [10, 12, 43, 14]])

## Vector Operations:
#### Addition

Given v is a vector and w is a vector

v + w = [v1 + w1, v2 + w2, ..., vn + wn]

In [ ]:
v = np.array([10, 20, 30, 40])
w = np.ones(4)

v + w

#### Subtraction
Given v is a vector and w is a vector

v - w = [v1 - w1, v2 - w2, ..., vn - wn]

In [8]:
v = np.array([10, 20, 30, 40])
w = np.ones(4)
v - w

array([ 9., 19., 29., 39.])

#### Multiplication
Given v is a vector and w is a vector

v * w = [v1 * w1, v2 * w2, ..., vn * wn]

In [9]:
v = np.array([10, 20, 30, 40])
w = np.array([2, 2, 2, 2])
v * w

array([20, 40, 60, 80])

#### Division
Given v is a vector and w is a vector

v / w = [v1 / w1, v2 / w2, ..., vn / wn]

In [10]:
v = np.array([10, 20, 30, 40])
w = np.array([2, 2, 2, 2])
v / w

array([ 5., 10., 15., 20.])

## Matrix Operations:
#### Matrix addition and subtraction.

In [13]:
# Addition
matrix = np.array([[10, 20, 30],
                   [20, 30, 40],
                   [30, 40, 50]])

ten = 10
ten + matrix

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [12]:
# Subtraction
ten - matrix

array([[  0, -10, -20],
       [  0, -10, -20],
       [  0, -10, -20]])

In [14]:
matrix - ten

array([[ 0, 10, 20],
       [10, 20, 30],
       [20, 30, 40]])

#### Scalar multiplication and division for matrices.

In [16]:
# Multiplication
matrix = np.array([[10, 20, 30],
                   [20, 30, 40],
                   [30, 40, 50]])

ten = 10

matrix * ten

array([[100, 200, 300],
       [200, 300, 400],
       [300, 400, 500]])

In [17]:
# Division
matrix = np.array([[10, 20, 30],
                   [20, 30, 40],
                   [30, 40, 50]])

ten = 10

matrix / ten

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

#### Vector Vector Multiplication.

Returns a value

In [29]:
v1 = np.array([10,20])
v2 = np.array([10,20])

v1.dot(v2)

500

#### Matrix multiplication (a fundamental operation used in linear regression).

In [30]:
# square matrices
matrix_x = np.array([[10, 20],
                     [20, 30]])

matrix_y = np.array([[1, 2],
                     [3, 4]])

# [[70, 100],
#  [110, 160]]

# matrix_x.dot(matrix_y)
matrix_x, matrix_y

# transpose
matrix_x.dot(matrix_y)

array([[ 70, 100],
       [110, 160]])

In [ ]:
# not square matrices
matrix_x = np.array([[10, 20],
                     [20, 30],
                     [40, 50]])

matrix_y = np.array([[1, 2],
                     [3, 4]])